version: '3'
services:
  server:
    image: server:latest
    ports:
      - "8761:8761"
  csp:
    image: csp:latest
    depends_on:
      -server
    ports:
      - "8080:8080"
  api-gateway:
    image: api-gateway:latest
    depends_on:
      -server
    ports:
      - "8082:8082"
